// ============================================
// AI.DY — Database types
// PLACEHOLDER — auto-generated by `pnpm db:types` from the live schema.
// Will be overwritten once the schema is migrated.
// ============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>; // populated after first migration
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
